version: '3.8'

services:
  rclone-filebrowser:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: rclone-filebrowser
    ports:
      - "8080:8080"
    cap_add:
      - SYS_ADMIN
    devices:
      - "/dev/fuse:/dev/fuse"
    # volumes:
    #   - ./rclone.conf:/config/rclone/rclone.conf
    security_opt:
      - apparmor:unconfined
    env_file:
      - .env
    command: /start.sh
    restart: unless-stopped
